sudo: required
language: generic

services:
  - docker

before_install: 
  - docker build -t rahulkumartonk/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rahulkumartonk/react-test npm run test --coverage

after_success: 
  - docker build -t rahulkumartonk/multi-client ./client
  - docker build -t rahulkumartonk/multi-nginx ./nginx
  - docker build -t rahulkumartonk/multi-server ./server
  - docker build -t rahulkumartonk/multi-worker ./worker
    # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push rahulkumartonk/multi-client
  - docker push rahulkumartonk/multi-nginx
  - docker push rahulkumartonk/multi-server
  - docker push rahulkumartonk/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-771007389696"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"

